version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd builder
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm build
  post_build:
    commands:
      # copy the contents of /build to S3
      #- aws s3 cp build/ s3://builder-service-s3 --recursive
      # - npm run-script claudia-dev
artifacts:
  files:
    - '**/*'
  base-directory: builder/build

